import hash from "object-hash";

// Casinos images
import wineCasino_mini from "./../../components/variants/src/image1.png";
import wineCasino_middle from "./../../components/variants/src/image2.png";
import wineCasino_maxi from "./../../components/variants/src/image3.png";
import wineCasinoCart from "../../components/cart/src/wineCasinoImage.png";

// Equipment images
import chairClassic from "../../components/additionals/src/chairClassic.png";
import chairKyara from "../../components/additionals/src/chair.png";
import chairLeather from "../../components/additionals/src/leatherChair.png";
import cash from "../../components/additionals/src/cash.png";

// Services images
import pitBoss from "../../components/additionals/src/pitBoss.png";
import magician from "../../components/additionals/src/magician.png";
import thimblerigger from "../../components/additionals/src/thimblerigger.png";

// Kind of Games image
import roulette from "../../components/kindsOfGames/src/image.png";

/** Casino cart icons */
import attractionMiniIcon from "./defaultCasinos/src/casinoCartIcons/attraction.png";
import automatsMiniIcon from "./defaultCasinos/src/casinoCartIcons/automats.png";
import beerMiniIcon from "./defaultCasinos/src/casinoCartIcons/beer.png";
import bilyardMiniIcon from "./defaultCasinos/src/casinoCartIcons/bilyard.png";
import blackJackMiniIcon from "./defaultCasinos/src/casinoCartIcons/blackJack.png";
import breadMiniIcon from "./defaultCasinos/src/casinoCartIcons/bread.png";
import champagneMiniIcon from "./defaultCasinos/src/casinoCartIcons/champagne.png";
import cheeseMiniIcon from "./defaultCasinos/src/casinoCartIcons/cheese.png";
import chilliMiniIcon from "./defaultCasinos/src/casinoCartIcons/chilli.png";
import chocolateMiniIcon from "./defaultCasinos/src/casinoCartIcons/chocolate.png";
import coffeeMiniIcon from "./defaultCasinos/src/casinoCartIcons/coffee.png";
import crapsMiniIcon from "./defaultCasinos/src/casinoCartIcons/craps.png";
import fatMiniIcon from "./defaultCasinos/src/casinoCartIcons/fat.png";
import honeyMiniIcon from "./defaultCasinos/src/casinoCartIcons/honey.png";
import kolesoMiniIcon from "./defaultCasinos/src/casinoCartIcons/koleso.png";
import limonadMiniIcon from "./defaultCasinos/src/casinoCartIcons/limonad.png";
import liquorMiniIcon from "./defaultCasinos/src/casinoCartIcons/liquor.png";
import molecularMiniIcon from "./defaultCasinos/src/casinoCartIcons/molecular.png";
import onlineMiniIcon from "./defaultCasinos/src/casinoCartIcons/online.png";
import pokerMiniIcon from "./defaultCasinos/src/casinoCartIcons/poker.png";
import ruletkaMiniIcon from "./defaultCasinos/src/casinoCartIcons/ruletka.png";
import stakeMiniIcon from "./defaultCasinos/src/casinoCartIcons/stake.png";
import teaMiniIcon from "./defaultCasinos/src/casinoCartIcons/tea.png";
import tinctureMiniIcon from "./defaultCasinos/src/casinoCartIcons/tincture.png";
import whiskeyMiniIcon from "./defaultCasinos/src/casinoCartIcons/whiskey.png";

const positions = [
  {
    title: "Стул-классика",
    image: { normal: chairClassic, cart: chairClassic },
    price: 1500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-классика",
  },
  {
    title: "Стул-кьяра",
    image: { normal: chairKyara, cart: chairKyara },
    price: 2000,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-кьяра",
  },
  {
    title: "Кожаный стул",
    image: { normal: chairLeather, cart: chairLeather },
    price: 2500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Кожаный стул",
  },
  {
    title: "Брендированые фан-мани",
    image: { normal: cash, cart: cash },
    price: 500,
    count: { title: "100 купюр", value: 100, fixed: false },
    type: "equipment",
    cartTitle: "Брендированые фан-мани",
  },
  {
    title: "Стул-классика1",
    image: { normal: chairClassic, cart: chairClassic },
    price: 1500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-классика",
  },
  {
    title: "Стул-кьяра1",
    image: { normal: chairKyara, cart: chairKyara },
    price: 2000,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-кьяра",
  },
  {
    title: "Кожаный стул1",
    image: { normal: chairLeather, cart: chairLeather },
    price: 2500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Кожаный стул",
  },
  {
    title: "Брендированые фан-мани1",
    image: { normal: cash, cart: cash },
    price: 500,
    count: { title: "100 купюр", value: 100, fixed: false },
    type: "equipment",
    cartTitle: "Брендированые фан-мани",
  },
  {
    title: "Стул-классика2",
    image: { normal: chairClassic, cart: chairClassic },
    price: 1500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-классика",
  },
  {
    title: "Стул-кьяра2",
    image: { normal: chairKyara, cart: chairKyara },
    price: 2000,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-кьяра",
  },
  {
    title: "Кожаный стул2",
    image: { normal: chairLeather, cart: chairLeather },
    price: 2500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Кожаный стул",
  },
  {
    title: "Брендированые фан-мани2",
    image: { normal: cash, cart: cash },
    price: 500,
    count: { title: "100 купюр", value: 100, fixed: false },
    type: "equipment",
    cartTitle: "Брендированые фан-мани",
  },

  {
    title: "Пит-босс",
    image: { normal: pitBoss, cart: pitBoss },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "курирует работу крупье",
    cartTitle: "Пит-босс",
  },
  {
    title: "Фокусник",
    image: { normal: magician, cart: magician },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "проведет незабываемое шоу",
    cartTitle: "Фокусник",
  },
  {
    title: "Напёрсточник",
    image: { normal: thimblerigger, cart: thimblerigger },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "сделает ваш вечер более запутанным, но интригующим",
    cartTitle: "Напёрсточник",
  },
  {
    title: "Пит-босс1",
    image: { normal: pitBoss, cart: pitBoss },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "курирует работу крупье",
    cartTitle: "Пит-босс",
  },
  {
    title: "Фокусник1",
    image: { normal: magician, cart: magician },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "проведет незабываемое шоу",
    cartTitle: "Фокусник",
  },
  {
    title: "Напёрсточник1",
    image: { normal: thimblerigger, cart: thimblerigger },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "сделает ваш вечер более запутанным, но интригующим",
    cartTitle: "Напёрсточник",
  },
  {
    title: "Пит-босс2",
    image: { normal: pitBoss, cart: pitBoss },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "курирует работу крупье",
    cartTitle: "Пит-босс",
  },
  {
    title: "Фокусник2",
    image: { normal: magician, cart: magician },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "проведет незабываемое шоу",
    cartTitle: "Фокусник",
  },
  {
    title: "Напёрсточник2",
    image: { normal: thimblerigger, cart: thimblerigger },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "сделает ваш вечер более запутанным, но интригующим",
    cartTitle: "Напёрсточник",
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: wineCasinoCart },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "wine",
    cartTitle: "Винное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: wineCasinoCart },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "wine",
    cartTitle: "Винное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: wineCasinoCart },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "wine",
    cartTitle: "Винное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: cheeseMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "cheese",
    cartTitle: "Сырное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: cheeseMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "cheese",
    cartTitle: "Сырное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: cheeseMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "cheese",
    cartTitle: "Сырное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: chocolateMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chocolate",
    cartTitle: "Шоколадное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: chocolateMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "chocolate",
    cartTitle: "Шоколадное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: chocolateMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chocolate",
    cartTitle: "Шоколадное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    type: "poker",
    title: "Французская",
    cartTitle: "Французская рулетка",
    image: {
      cart: roulette,
    },
    images: [roulette, roulette, roulette, roulette, roulette],
    price: 18000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "lorem ipsum1",
        "lorem ipsum2",
        "lorem ipsum3",
        "lorem ipsum4",
        "lorem ipsum5",
        "lorem ipsum6",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 13333",
        "Колесо - 1333 комплект3333",
        "Комплект Фишки - 13333",
        "Крупье - 13333 чел.",
      ],
    },
  },
  {
    type: "poker",
    title: "Классическая",
    cartTitle: "Классическая рулетка",
    image: {
      cart: roulette,
    },
    images: [roulette, roulette, roulette, roulette, roulette],
    price: 10000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "lorem ipsum132",
        "lorem ipsum232",
        "lorem ipsum332",
        "lorem ipsum432",
        "lorem ipsum532",
        "lorem ipsum632",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: teaMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: teaMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: teaMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: limonadMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "nonalcoholic",
    cartTitle: "Безалкогольное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: limonadMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "nonalcoholic",
    cartTitle: "Безалкогольное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: limonadMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "nonalcoholic",
    cartTitle: "Безалкогольное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: coffeeMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "coffee",
    cartTitle: "Кофейное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: coffeeMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "coffee",
    cartTitle: "Кофейное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: coffeeMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "coffee",
    cartTitle: "Кофейное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: champagneMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "champgane",
    cartTitle: "Шампанское казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: champagneMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "champgane",
    cartTitle: "Шампанское казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: champagneMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "champgane",
    cartTitle: "Шампанское казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: honeyMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "honey",
    cartTitle: "Медовое казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: honeyMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "honey",
    cartTitle: "Медовое казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: honeyMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "honey",
    cartTitle: "Медовое казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: breadMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "bread",
    cartTitle: "Хлебное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: breadMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "bread",
    cartTitle: "Хлебное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: breadMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "bread",
    cartTitle: "Хлебное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: teaMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: teaMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: teaMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: fatMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "fat",
    cartTitle: "Сало казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: fatMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "fat",
    cartTitle: "Сало казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: fatMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "fat",
    cartTitle: "Сало казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: stakeMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "meat",
    cartTitle: "Мясное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: stakeMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "meat",
    cartTitle: "Мясное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: stakeMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "meat",
    cartTitle: "Мясное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: whiskeyMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "whiskey",
    cartTitle: "Виски казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: whiskeyMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "whiskey",
    cartTitle: "Виски казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: whiskeyMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "whiskey",
    cartTitle: "Виски казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: beerMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "beer",
    cartTitle: "Пивное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: beerMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "beer",
    cartTitle: "Пивное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: beerMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "beer",
    cartTitle: "Пивное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: tinctureMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tincture",
    cartTitle: "Настойки казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: tinctureMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "tincture",
    cartTitle: "Настойки казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: tinctureMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tincture",
    cartTitle: "Настойки казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: liquorMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "liquor",
    cartTitle: "Ликерное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: liquorMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "liquor",
    cartTitle: "Ликерное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: liquorMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "liquor",
    cartTitle: "Ликерное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: molecularMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "molecular",
    cartTitle: "Молекулярное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: molecularMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "molecular",
    cartTitle: "Молекулярное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: molecularMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "molecular",
    cartTitle: "Молекулярное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: chilliMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chilli",
    cartTitle: "Чили казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: chilliMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "chilli",
    cartTitle: "Чили казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: chilliMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chilli",
    cartTitle: "Чили казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },
];

const positionsWithId = positions.map((item) => ({ ...item, id: hash(item) }));

export default positionsWithId;
