import hash from "object-hash";

// Casinos images
import wineCasino_mini from "../../../components/variants/src/image1.png";
import wineCasino_middle from "../../../components/variants/src/image2.png";
import wineCasino_maxi from "../../../components/variants/src/image3.png";
import wineCasinoCart from "../../../components/cart/src/wineCasinoImage.png";

// Equipment images
import chairClassic from "../../../components/additionals/src/chairClassic.png";
import chairKyara from "../../../components/additionals/src/chair.png";
import chairLeather from "../../../components/additionals/src/leatherChair.png";
import cash from "../../../components/additionals/src/cash.png";

// Services images
import pitBoss from "../../../components/additionals/src/pitBoss.png";
import magician from "../../../components/additionals/src/magician.png";
import thimblerigger from "../../../components/additionals/src/thimblerigger.png";

// Kind of Games image
import roulette from "../../../components/kindsOfGames/src/image.png";

/** Casino cart icons */
import attractionMiniIcon from "../defaultCasinos/src/casinoCartIcons/attraction.png";
import automatsMiniIcon from "../defaultCasinos/src/casinoCartIcons/automats.png";
import beerMiniIcon from "../defaultCasinos/src/casinoCartIcons/beer.png";
import bilyardMiniIcon from "../defaultCasinos/src/casinoCartIcons/bilyard.png";
import blackJackMiniIcon from "../defaultCasinos/src/casinoCartIcons/blackJack.png";
import breadMiniIcon from "../defaultCasinos/src/casinoCartIcons/bread.png";
import champagneMiniIcon from "../defaultCasinos/src/casinoCartIcons/champagne.png";
import cheeseMiniIcon from "../defaultCasinos/src/casinoCartIcons/cheese.png";
import chilliMiniIcon from "../defaultCasinos/src/casinoCartIcons/chilli.png";
import chocolateMiniIcon from "../defaultCasinos/src/casinoCartIcons/chocolate.png";
import coffeeMiniIcon from "../defaultCasinos/src/casinoCartIcons/coffee.png";
import crapsMiniIcon from "../defaultCasinos/src/casinoCartIcons/craps.png";
import fatMiniIcon from "../defaultCasinos/src/casinoCartIcons/fat.png";
import honeyMiniIcon from "../defaultCasinos/src/casinoCartIcons/honey.png";
import kolesoMiniIcon from "../defaultCasinos/src/casinoCartIcons/koleso.png";
import limonadMiniIcon from "../defaultCasinos/src/casinoCartIcons/limonad.png";
import liquorMiniIcon from "../defaultCasinos/src/casinoCartIcons/liquor.png";
import molecularMiniIcon from "../defaultCasinos/src/casinoCartIcons/molecular.png";
import onlineMiniIcon from "../defaultCasinos/src/casinoCartIcons/online.png";
import pokerMiniIcon from "../defaultCasinos/src/casinoCartIcons/poker.png";
import ruletkaMiniIcon from "../defaultCasinos/src/casinoCartIcons/ruletka.png";
import stakeMiniIcon from "../defaultCasinos/src/casinoCartIcons/stake.png";
import teaMiniIcon from "../defaultCasinos/src/casinoCartIcons/tea.png";
import tinctureMiniIcon from "../defaultCasinos/src/casinoCartIcons/tincture.png";
import whiskeyMiniIcon from "../defaultCasinos/src/casinoCartIcons/whiskey.png";

/* Ruletka */
import classicRuletka from "./src/ruletka/classic.png";
import frenchRuletka from "./src/ruletka/french.png";
import gambleRuletka from "./src/ruletka/gamble.png";
import amateurRuletka from "./src/ruletka/amateur.png";
import scandinavianRuletka from "./src/ruletka/scandinavian.png";
import vipRuletka from "./src/ruletka/vip.png";

/* Poker */
import fortunaPoker from "./src/poker/fortuna.png";

/* BlackJack */
import gamingBlackJack from "./src/blackJack/gaming.png";

/* Craps */
import greenDiceCraps from "./src/craps/greenDice.png";

/* Automats */
import automatAutomats from "./src/automats/automat.png";

/* Online */
import blackJackonline from "./src/online/blackJack.png";

/* Attractions */
import magicBallAttraction from "./src/attractions/magicBall.png";

const positions = [
  {
    title: "Стул-классика",
    image: { normal: chairClassic, cart: chairClassic },
    price: 1500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-классика",
  },
  {
    title: "Стул-кьяра",
    image: { normal: chairKyara, cart: chairKyara },
    price: 2000,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-кьяра",
  },
  {
    title: "Кожаный стул",
    image: { normal: chairLeather, cart: chairLeather },
    price: 2500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Кожаный стул",
  },
  {
    title: "Брендированые фан-мани",
    image: { normal: cash, cart: cash },
    price: 500,
    count: { title: "100 купюр", value: 100, fixed: false },
    type: "equipment",
    cartTitle: "Брендированые фан-мани",
  },
  {
    title: "Стул-классика1",
    image: { normal: chairClassic, cart: chairClassic },
    price: 1500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-классика",
  },
  {
    title: "Стул-кьяра1",
    image: { normal: chairKyara, cart: chairKyara },
    price: 2000,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-кьяра",
  },
  {
    title: "Кожаный стул1",
    image: { normal: chairLeather, cart: chairLeather },
    price: 2500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Кожаный стул",
  },
  {
    title: "Брендированые фан-мани1",
    image: { normal: cash, cart: cash },
    price: 500,
    count: { title: "100 купюр", value: 100, fixed: false },
    type: "equipment",
    cartTitle: "Брендированые фан-мани",
  },
  {
    title: "Стул-классика2",
    image: { normal: chairClassic, cart: chairClassic },
    price: 1500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-классика",
  },
  {
    title: "Стул-кьяра2",
    image: { normal: chairKyara, cart: chairKyara },
    price: 2000,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Стул-кьяра",
  },
  {
    title: "Кожаный стул2",
    image: { normal: chairLeather, cart: chairLeather },
    price: 2500,
    count: { title: "за шт", value: 1, fixed: false },
    type: "equipment",
    cartTitle: "Кожаный стул",
  },
  {
    title: "Брендированые фан-мани2",
    image: { normal: cash, cart: cash },
    price: 500,
    count: { title: "100 купюр", value: 100, fixed: false },
    type: "equipment",
    cartTitle: "Брендированые фан-мани",
  },

  {
    title: "Пит-босс",
    image: { normal: pitBoss, cart: pitBoss },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "курирует работу крупье",
    cartTitle: "Пит-босс",
  },
  {
    title: "Фокусник",
    image: { normal: magician, cart: magician },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "проведет незабываемое шоу",
    cartTitle: "Фокусник",
  },
  {
    title: "Напёрсточник",
    image: { normal: thimblerigger, cart: thimblerigger },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "сделает ваш вечер более запутанным, но интригующим",
    cartTitle: "Напёрсточник",
  },
  {
    title: "Пит-босс1",
    image: { normal: pitBoss, cart: pitBoss },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "курирует работу крупье",
    cartTitle: "Пит-босс",
  },
  {
    title: "Фокусник1",
    image: { normal: magician, cart: magician },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "проведет незабываемое шоу",
    cartTitle: "Фокусник",
  },
  {
    title: "Напёрсточник1",
    image: { normal: thimblerigger, cart: thimblerigger },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "сделает ваш вечер более запутанным, но интригующим",
    cartTitle: "Напёрсточник",
  },
  {
    title: "Пит-босс2",
    image: { normal: pitBoss, cart: pitBoss },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "курирует работу крупье",
    cartTitle: "Пит-босс",
  },
  {
    title: "Фокусник2",
    image: { normal: magician, cart: magician },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "проведет незабываемое шоу",
    cartTitle: "Фокусник",
  },
  {
    title: "Напёрсточник2",
    image: { normal: thimblerigger, cart: thimblerigger },
    price: 8000,
    count: { fixed: true, value: 1 },
    type: "service",
    description: "сделает ваш вечер более запутанным, но интригующим",
    cartTitle: "Напёрсточник",
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: wineCasinoCart },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "wine",
    cartTitle: "Винное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: wineCasinoCart },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "wine",
    cartTitle: "Винное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: wineCasinoCart },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "wine",
    cartTitle: "Винное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: cheeseMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "cheese",
    cartTitle: "Сырное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: cheeseMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "cheese",
    cartTitle: "Сырное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: cheeseMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "cheese",
    cartTitle: "Сырное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: chocolateMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chocolate",
    cartTitle: "Шоколадное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: chocolateMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "chocolate",
    cartTitle: "Шоколадное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: chocolateMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chocolate",
    cartTitle: "Шоколадное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  /* Ruletka */
  {
    type: "casino",
    casinoType: "ruletka",
    title: "Классическая",
    cartTitle: "Классическая рулетка",
    image: {
      cart: ruletkaMiniIcon,
    },
    images: [roulette, roulette, roulette, roulette, roulette],
    price: 10000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "lorem ipsum132",
        "lorem ipsum232",
        "lorem ipsum332",
        "lorem ipsum432",
        "lorem ipsum532",
        "lorem ipsum632",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Французская",
    cartTitle: "Французская рулетка",
    type: "casino",
    casinoType: "ruletka",
    image: {
      cart: ruletkaMiniIcon,
    },
    images: [frenchRuletka, frenchRuletka, frenchRuletka, frenchRuletka],
    price: 18000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "«Рулетка» по-французски – игра, не требующая особых знаний и навыков. Данный вариант «Рулетки» практически полностью повторяет классический. Единственные отличия – уменьшенный диаметр вращающегося колеса и оформление поля. Правила игры все те же: игроку нужно предугадать, куда угодит шарик.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Гэмбл",
    cartTitle: "Гэмбл рулетка",
    type: "casino",
    casinoType: "ruletka",
    image: {
      cart: ruletkaMiniIcon,
    },
    images: [
      gambleRuletka,
      gambleRuletka,
      gambleRuletka,
      gambleRuletka,
      gambleRuletka,
    ],
    price: 18000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Фан-казино, победитель в котором определяется через «колесо фортуны». Именно это и является основной фишкой данной игры: участникам не нужно прикладывать особых усилий и обдумывать свои действия. Гэмбл непременно станет центром притяжения на любом мероприятии и вовлечет гостей в атмосферу азарта.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Любительская",
    cartTitle: "Любительская рулетка",
    type: "casino",
    casinoType: "ruletka",
    image: {
      cart: ruletkaMiniIcon,
    },
    images: [
      amateurRuletka,
      amateurRuletka,
      amateurRuletka,
      amateurRuletka,
      amateurRuletka,
    ],
    price: 18000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Планируете организовать выездное мини-казино для ваших коллег или друзей? Самое время заказать аренду маленького стола для игры в «Рулетку». Его отличают компактные размеры, простейшие правила игры и яркий дизайн. Все, что нужно для игры – небольшой набор из вращающегося колеса, столика и фишек.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Скандинавская",
    cartTitle: "Скандинавская рулетка",
    type: "casino",
    casinoType: "ruletka",
    image: {
      cart: ruletkaMiniIcon,
    },
    images: [
      scandinavianRuletka,
      scandinavianRuletka,
      scandinavianRuletka,
      scandinavianRuletka,
      scandinavianRuletka,
    ],
    price: 18000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Упрощенный вариант традиционной «Рулетки», идеально подходящий для организации фан-казино на выезде. Колесо рассчитано всего на шесть секторов, что существенно повышает шансы на выигрыш. Правила игры полностью аналогичны классической рулетке. При желании у нас можно заказать брендирование и уникальный дизайн стола.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "VIP-рулетка",
    cartTitle: "VIP-рулетка",
    type: "casino",
    casinoType: "ruletka",
    image: {
      cart: ruletkaMiniIcon,
    },
    images: [vipRuletka, vipRuletka, vipRuletka, vipRuletka, vipRuletka],
    price: 18000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Роскошный белый игровой стол, призванный стать центром для азартных развлечений на любом празднике. Игра в рулетку полностью зависит от удачливости игрока и лишь самую малость – от его меткости. Стол для игры в ВИП-рулетку выполнен из премиальных материалов и устойчив к появлению царапин.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  /* Poker */
  {
    title: "Фортуна",
    cartTitle: "Фортуна покер",
    type: "casino",
    casinoType: "poker",
    image: {
      cart: pokerMiniIcon,
    },
    images: [
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
    ],
    price: 17000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Карточная игра, полностью основанная на выпадении карт. Победителем Фортуны становится игрок, сделавший правильную ставку. Дилер мастерски перемешивает колоду и сбрасывает на стол четыре карты, и лишь удача определит, насколько успешна их комбинация. Отличная идея для выездного фан-казино в ресторане, ночном клубе и даже в офисе.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Любительский",
    cartTitle: "Любительский покер",
    type: "casino",
    casinoType: "poker",
    image: {
      cart: pokerMiniIcon,
    },
    images: [
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
    ],
    price: 17000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Бюджетный полукруглый стол для игры в покер. Несмотря на компактные размеры, его вполне достаточно для полноценного игрового процесса. Стол рассчитан на 4-7 игроков, выполнен из качественных материалов. Карты и фишки включены в стоимость базового комплекта.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Профессиональный",
    cartTitle: "Профессиональный покер",
    type: "casino",
    casinoType: "poker",
    image: {
      cart: pokerMiniIcon,
    },
    images: [
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
    ],
    price: 17000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Качественный полукруглый стол, предназначенный для традиционного покера. Данная версия покерного стола – наиболее распространенная в мире. Стол выполнен из натурального дерева, обтянут кожей и сукном. Максимальное количество игроков – семь человек.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Premium",
    cartTitle: "Premium покер",
    type: "casino",
    casinoType: "poker",
    image: {
      cart: pokerMiniIcon,
    },
    images: [
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
    ],
    price: 17000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Желаете арендовать для вашего мероприятия настоящий стол для покера? Компания фан-казино предлагает качественный стол-реплику покерного стола, выполненного в стилистике казино. Премиальный стол предназначен для профессиональной игры в покер. По периметру он оснащен светодиодной ленточной подсветкой, что делает его идеальным решением для игры в полумраке.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Спортивный",
    cartTitle: "Спортивный покер",
    type: "casino",
    casinoType: "poker",
    image: {
      cart: pokerMiniIcon,
    },
    images: [
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
    ],
    price: 17000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Покерный стол, рассчитанный на большую компанию игроков. Одновременно вмещает от семи до десяти человек. Отличается просторной поверхностью, мягкой овальной формой и удобством. Спортивный покерный стол – отличный выбор для профессиональных соревнований по игре в покер. При желании его можно арендовать на любое мероприятие.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Индийский",
    cartTitle: "Индийский покер",
    type: "casino",
    casinoType: "poker",
    image: {
      cart: pokerMiniIcon,
    },
    images: [
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
      fortunaPoker,
    ],
    price: 17000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Вы когда-нибудь слышали про индийский покер? Данная игра отлична тем, что подходит как для двух игроков, так и для целой команды (до девяти человек). Прежде чем раздать карты, необходимо определить раздающего игрока. Последний становится обладателем фишки дилера, чтобы не забыть о последовательности.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  /* BlackJack */
  {
    title: "Игровой",
    cartTitle: "Игровой Блэк Джэк",
    type: "casino",
    casinoType: "blackJack",
    image: {
      cart: blackJackMiniIcon,
    },
    images: [
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Если вы хотите организовать выездную игру в блэкджек небольшой компанией, рекомендуем выбрать бюджетную версию игрового стола. В отличие от покера, игроки противостоят ведущему или дилеру, не играя друг против друга. Главная цель каждого игрока – заработать максимальное количество баллов, но не более 21 очка.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Прокатный",
    cartTitle: "Прокатный Блэк Джэк",
    type: "casino",
    casinoType: "blackJack",
    image: {
      cart: blackJackMiniIcon,
    },
    images: [
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Традиционная модель стола для игры в блэк джек, за которым могут собраться как новички, так и истинные профи. Данный стол отлично подойдет для любых мероприятий, подходит для залов казино, ресторанов и даже офисов. Мы гарантируем высокое качество материалов изготовления: стол не подвержен появлению царапин и очень удобен в использовании.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Корпоративный",
    cartTitle: "Корпоративный Блэк Джэк",
    type: "casino",
    casinoType: "blackJack",
    image: {
      cart: blackJackMiniIcon,
    },
    images: [
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Игровой аттракцион, рассчитанный на большую команду игроков. Станет идеальным дополнением корпоративного праздника или эффектным завершением деловых переговоров. Стандартная комплектация набора включает игровой стол, карточный шуз, карты, фишки, флот. Также у нас можно заказать услуги профессионального крупье.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Premium",
    cartTitle: "Premium Блэк Джэк",
    type: "casino",
    casinoType: "blackJack",
    image: {
      cart: blackJackMiniIcon,
    },
    images: [
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
      gamingBlackJack,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Заказывая премиум-стол для игры в блэк джек в фан-казино, вы делаете выбор в пользу стильной и статусной зоны фан-казино. Благодаря ленточной подсветке стол можно расположить в зоне полумрака, погрузив игроков в таинственную атмосферу. В стоимость аренды включены стол, шуз для карт, карты, флот, фишки и услуги крупье.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  /* Craps */
  {
    title: "Green Dice",
    cartTitle: "Green Dice Крэпс",
    type: "casino",
    casinoType: "craps",
    image: {
      cart: crapsMiniIcon,
    },
    images: [
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Обновленная версия игры в крэпс, по правилам которой вместо двух кубиков подбрасываются три. Тем самым ставки на числа становятся не столько рискованными, но при этом обеспечивают максимальный выигрыш. В каждом раунде игроку необходимо делать ставки, а дилеру – неоднократно перевернуть клетку с игровыми кубиками.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Классический",
    cartTitle: "Классический Крэпс",
    type: "casino",
    casinoType: "craps",
    image: {
      cart: crapsMiniIcon,
    },
    images: [
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "В стандартную комплектацию фан-казино входят:",
        "•	карты;",
        "•	игровые фишки;",
        "•	стол;",
        "•	фишки;",
        "•	услуги профессионального крупье.",
        " ",
        "Стол выполнен из высококачественных материалов, устойчивых к появлению царапин. За дополнительную плату можно заказать брендирование любого стола для крэпс.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Корпоративный",
    cartTitle: "Корпоративный Крэпс",
    type: "casino",
    casinoType: "craps",
    image: {
      cart: crapsMiniIcon,
    },
    images: [
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Еще одна вариация игры в крэпс, позволяющая получить невероятное удовольствие от процесса на любом мероприятии. Наша компания фан-казино предлагает полноценные наборы для игры в корпоративный крэпс по доступной цене. Стол отличается ярким дизайном, притягивающим гостей.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Клубный",
    cartTitle: "Клубный Крэпс",
    type: "casino",
    casinoType: "craps",
    image: {
      cart: crapsMiniIcon,
    },
    images: [
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
      greenDiceCraps,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Если вы хотите собрать за столом опытных игроков в крэпс, лучшим решением станет аренда профессионального стола. В каталоге компании фан-казино представлены роскошные игровые столы, изготовленные из натурального дерева. При желании также можно заказать эксклюзивное оформление стола.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  /** Automats */
  {
    title: "Прокатный",
    cartTitle: "Прокатный автома",
    type: "casino",
    casinoType: "automats",
    image: { cart: automatsMiniIcon },
    images: [
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Самый простой вариант игрового автомата, рассчитанный на одну игру. Тем не менее, такой модели вполне достаточно для небольшой компании игроков. Это лучший выбор для тех, кто желает поиграть в одиночку или организовать дуэль с парочкой друзей. Игровой автомат имеет компактные размеры и красочный дизайн.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Игровой",
    cartTitle: "Игровой автомат",
    type: "casino",
    casinoType: "automats",
    image: { cart: automatsMiniIcon },
    images: [
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Модель, рассчитанная на несколько азартных игр, известных каждому любителю казино. Автомат предлагает внушительный набор увлекательных игр различной тематики. игроки могут самостоятельно переключаться от одной игры к другой без посторонней помощи. ",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Однорукий бандит Vegas",
    cartTitle: "Однорукий бандит Vegas",
    type: "casino",
    casinoType: "automats",
    image: { cart: automatsMiniIcon },
    images: [
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Абсолютная классика мира казино и азартных игр. Автомат выполнен в стилистике знаменитого Лас-Вегаса. Для запуска барабана игроку достаточно просто дернуть рычажок, в честь чего автомат и получил имя «однорукий бандит». Аренда данной модели станет отличной идеей для развлечения гостей на любом празднике.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Игровой автомат Jack",
    cartTitle: "Игровой автомат Jack",
    type: "casino",
    casinoType: "automats",
    image: { cart: automatsMiniIcon },
    images: [
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Абсолютная классика мира казино и азартных игр. Автомат выполнен в стилистике знаменитого Лас-Вегаса. Для запуска барабана игроку достаточно просто дернуть рычажок, в честь чего автомат и получил имя «однорукий бандит». Аренда данной модели станет отличной идеей для развлечения гостей на любом празднике.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Игровой автомат Рулетка",
    cartTitle: "Игровой автомат Рулетка",
    type: "casino",
    casinoType: "automats",
    image: { cart: automatsMiniIcon },
    images: [
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Модель, предлагающая игрокам делать ставки по принципу традиционной рулетки. Благодаря этому шансы на выигрыш значительно выше по сравнению с другими игровыми автоматами (соотношение около 1:37, в зависимости от ставки). Игрокам доступен самостоятельный выбор цвета, числа или группы чисел.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Однорукий бандит HotLine",
    cartTitle: "Однорукий бандит HotLine",
    type: "casino",
    casinoType: "automats",
    image: { cart: automatsMiniIcon },
    images: [
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
      automatAutomats,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Очередная бессмертная классика игровой индустрии – «телефонная будка». Данный игровой автомат является разновидностью «однорукого бандита» и часто встречается на знаменитых чикагских вечеринках. Для запуска барабана достаточно бросить монетку и дернуть за рычажок.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  /* Online Casino */
  {
    title: "Блэк Джэк",
    cartTitle: "Блэк Джэк онлайн",
    type: "casino",
    casinoType: "online",
    image: { cart: onlineMiniIcon },
    images: [
      blackJackonline,
      blackJackonline,
      blackJackonline,
      blackJackonline,
      blackJackonline,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Одна из самых популярных карточных игр в мире, известная многим как 21 или «Очко». В нее принято играть в каждом казино, но сегодня она пользуется особым спросом среди онлайн-игроков. Несмотря на удаленный режим игры, правила остаются прежними:",
        "•	игрок делает ставку и получает две карты;",
        "•	его цель – набрать очков больше, чем крупье;",
        "•	при этом нельзя допускать перебора очков (их не должно быть больше 21).",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Рулетка",
    cartTitle: "Рулетка онлайн",
    type: "casino",
    casinoType: "online",
    image: { cart: onlineMiniIcon },
    images: [
      blackJackonline,
      blackJackonline,
      blackJackonline,
      blackJackonline,
      blackJackonline,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Не менее востребованная азартная игра с мировой популярностью. Рулетку воспевают популярные кинорежиссеры, создатели рекламы и прославленные артисты. Главная причина такой популярности рулетки – в ее очевидной простоте. Принцип игры состоит в том, что игрокам нужно делать ставки на игровом поле, после чего крупье раскручивает рулетку и вбрасывает шарик, угождающий в ту или иную ячейку. Побеждает игрок, угадывающий номер заветной ячейки.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  {
    title: "Крэпс",
    cartTitle: "Крэпс онлайн",
    type: "casino",
    casinoType: "online",
    image: { cart: onlineMiniIcon },
    images: [
      blackJackonline,
      blackJackonline,
      blackJackonline,
      blackJackonline,
      blackJackonline,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Как только появились первые фан-казино в формате онлайн, крэпс тут же оказался на виртуальных платформах. Компания фан-казино готова организовать полноценную онлайн-трансляцию столов по игре в крэпс на любое количество игроков. Для вбрасывания костей используются тачпад или мышь, выпадение чисел – исключительное случайное (во избежание мошенничества). За игровым процессом будет наблюдать опытный крупье.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  /* Attractions */
  {
    title: "Чудо-шар",
    cartTitle: "Чудо-шар",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Аттракцион, идеально подходящий даже самым маленьким детям. Оказаться в эффектном фотошаре совсем несложно: игроку даже не придется ничего делать для того, чтобы пошел снег. «Снегопад» начинается благодаря запуску вентиляторов, после чего взору гостей предстает невероятной красоты зрелище: снежная завеса, способная украсить любую фотографию.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Денежная кабина",
    cartTitle: "Денежная кабина",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Чтобы испытать незабываемые ощущения от игры, достаточно просто оказаться внутри кабины. Также данный аттракцион может использоваться для организации соревнований на любом мероприятии. Например, можно разбить игроков на группы и отправлять их внутрь кабины за деньгами поочередно. Победит тот, кто соберет максимальную сумму за определенное время.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Призовой аппарат Casino",
    cartTitle: "Призовой аппарат Casino",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Данный аттракцион – прекрасное решение для праздника с участием детей и взрослых. Цель игры проста: участникам нужно изрядно постараться, чтобы получить заветный приз. Для этого им предстоит сыграть в мини-игру, которая точно поднимет им настроение и зарядит позитивной энергией на долгое время.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Карточный стенд",
    cartTitle: "Карточный стенд",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Функциональный аттракцион, призванный стать эпицентром для развлечений на любом празднике. Он идеально подходит для организации конкурсов, эстафет, соревнований. Стенд позволяет насладиться самыми разными играми: от простого угадывания карточных пар до открытия тематических предметов и призов.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Карточный стол",
    cartTitle: "Карточный стол",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Наша команда сможем грамотно организовать необходимое оборудование, привести профессиональные столы для покера, блэкджека, баккары и других игр. Для всех желающих просто развлечь гостей не стареющей классикой типа пасьянса, дурака или преферанс у нас есть специальный стол в идеальной форме восьмигранника, рассчитанный на восьмерых человек.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Фишки Кэпсы",
    cartTitle: "Фишки Кэпсы",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Существует несколько увлекательных видов данной игры. В ней с «биткой», на поле выставляется стопка из соток, участники по очереди бьют по стопке биткой, при этом сила удара может быть любой. Перевернувшиеся сотки участник забирает себе, а по оставшимся бьет следующий участник. Так продолжается пока не останется соток. В рамках игры без битки, участники берутся пальцами за края нижней сотки и бьют ей по столу, забирая перевернувшиеся сотки.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Тараканьи бега",
    cartTitle: "Тараканьи бега",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Аттракцион, представленный в виде двухуровневой трассы для проведения знаменитых гонок с участием радиоуправляемых тараканов. Игра выглядит следующим образом: четыре «бегуна» управляются со специального пульта, и первый пришедший к финишу становится победителем. Все очень просто, но увлекательно.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Мышиные бега",
    cartTitle: "Мышиные бега",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Вариация тараканьих бегов с участием радиоуправляемых мышек. Принцип данного аттракциона предельно прост: мышки управляются дистанционно и соревнуются на двухуровневой трассе. При желании аттракцион можно совмещать с розыгрышем призов.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Тотализатор скачки",
    cartTitle: "Тотализатор скачки",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Классический аттракцион-тотализатор с полной игровой атрибутикой: видеоархив забегов, ставки, азартный настрой, профессиональный ведущий. Игрокам предстоят испытание на удачность и интуицию, а также погружение в атмосферу настоящего азарта.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Фотозона денежная ванна ",
    cartTitle: "Фотозона денежная ванна ",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Классический аттракцион-тотализатор с полной игровой атрибутикой: видеоархив забегов, ставки, азартный настрой, профессиональный ведущий. Игрокам предстоят испытание на удачность и интуицию, а также погружение в атмосферу настоящего азарта.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Кнопочные игровые автоматы ",
    cartTitle: "Кнопочные игровые автоматы ",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Классический аттракцион-тотализатор с полной игровой атрибутикой: видеоархив забегов, ставки, азартный настрой, профессиональный ведущий. Игрокам предстоят испытание на удачность и интуицию, а также погружение в атмосферу настоящего азарта.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },
  { 
    title: "Призовой аппарат золотой слиток ",
    cartTitle: "Призовой аппарат золотой слиток ",
    type: "casino",
    casinoType: "attraction",
    image: { cart: attractionMiniIcon },
    images: [
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
      magicBallAttraction,
    ],
    price: 14000,
    count: { fixed: true, value: 1 },
    time: 6,
    peopleCount: 6,
    description: {
      title: "Описание",
      items: [
        "Классический аттракцион-тотализатор с полной игровой атрибутикой: видеоархив забегов, ставки, азартный настрой, профессиональный ведущий. Игрокам предстоят испытание на удачность и интуицию, а также погружение в атмосферу настоящего азарта.",
      ],
    },
    characteristics: {
      title: "Общие требования",
      items: [
        "В стоимость включено:",
        "Игровой стол - 1",
        "Колесо - 1 комплект",
        "Комплект Фишки - 1",
        "Крупье - 1 чел.",
      ],
    },
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: champagneMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: teaMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: teaMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tea",
    cartTitle: "Чайное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: limonadMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "nonalcoholic",
    cartTitle: "Безалкогольное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: limonadMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "nonalcoholic",
    cartTitle: "Безалкогольное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: limonadMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "nonalcoholic",
    cartTitle: "Безалкогольное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: coffeeMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "coffee",
    cartTitle: "Кофейное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: coffeeMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "coffee",
    cartTitle: "Кофейное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: coffeeMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "coffee",
    cartTitle: "Кофейное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: champagneMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "champagne",
    cartTitle: "Шампанское казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: champagneMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "champagne",
    cartTitle: "Шампанское казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: champagneMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "champagne",
    cartTitle: "Шампанское казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: honeyMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "honey",
    cartTitle: "Медовое казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: honeyMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "honey",
    cartTitle: "Медовое казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: honeyMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "honey",
    cartTitle: "Медовое казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: breadMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "bread",
    cartTitle: "Хлебное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: breadMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "bread",
    cartTitle: "Хлебное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: breadMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "bread",
    cartTitle: "Хлебное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: fatMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "fat",
    cartTitle: "Сало казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: fatMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "fat",
    cartTitle: "Сало казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: fatMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "fat",
    cartTitle: "Сало казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: stakeMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "meat",
    cartTitle: "Мясное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: stakeMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "meat",
    cartTitle: "Мясное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: stakeMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "meat",
    cartTitle: "Мясное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: whiskeyMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "whiskey",
    cartTitle: "Виски казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: whiskeyMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "whiskey",
    cartTitle: "Виски казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: whiskeyMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "whiskey",
    cartTitle: "Виски казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: beerMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "beer",
    cartTitle: "Пивное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: beerMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "beer",
    cartTitle: "Пивное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: beerMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "beer",
    cartTitle: "Пивное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: tinctureMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tincture",
    cartTitle: "Настойки казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: tinctureMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "tincture",
    cartTitle: "Настойки казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: tinctureMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "tincture",
    cartTitle: "Настойки казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: liquorMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "liquor",
    cartTitle: "Ликерное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: liquorMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "liquor",
    cartTitle: "Ликерное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: liquorMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "liquor",
    cartTitle: "Ликерное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: molecularMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "molecular",
    cartTitle: "Молекулярное казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: molecularMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "molecular",
    cartTitle: "Молекулярное казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: molecularMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "molecular",
    cartTitle: "Молекулярное казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },

  {
    title: "Пакет — «Mini»",
    image: { normal: wineCasino_mini, cart: chilliMiniIcon },
    price: 34000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chilli",
    cartTitle: "Чили казино",
    cartItemDescription: "Mini пакет",
    description: "до 15 человек | до 2-х часов",
    isPopular: false,
    options: [
      "до 15 человек",
      "до 2-х часов работы",
      "услуги аниматора",
      "малое игровое полотно",
      "импортное вино — 4 сорта",
      "пластиковые бокалы",
    ],
  },
  {
    title: "Пакет — «Middle»",
    image: { normal: wineCasino_middle, cart: chilliMiniIcon },
    price: 64000,
    count: { fixed: false, value: 1 },
    type: "casino",
    casinoType: "chilli",
    cartTitle: "Чили казино",
    cartItemDescription: "Middle пакет",
    description: "до 50 человек | до 3-х часов",
    isPopular: true,
    options: [
      "до 50 человек",
      "до 3-х часов работы",
      "услуги сомелье",
      "большое игровое полотно",
      "импортное вино — 8 сортов",
      "пластиковые бокалы премиум",
      "подарочный набор — 10 бутылочек",
    ],
  },
  {
    title: "Пакет — «Maxi»",
    image: { normal: wineCasino_maxi, cart: chilliMiniIcon },
    price: 79000,
    count: { value: 1, fixed: false },
    type: "casino",
    casinoType: "chilli",
    cartTitle: "Чили казино",
    cartItemDescription: "Maxi пакет",
    description: "до 100 человек | до 4-х часов",
    isPopular: false,
    options: [
      "до 100 человек",
      "до 4-х часов работы",
      "услуги сомелье",
      "игровой стол",
      "импортное вино — 10 сортов",
      "стеклянные бокалы",
      "чехлы для бутылок",
      "официант и закуски",
      "подарочный набор — 20 бутылочек",
    ],
  },
];

const positionsWithId = positions.map((item) => ({ ...item, id: hash(item) }));

export default positionsWithId;
